name: testing
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push:
    branches:
      - main
  pull_request: 
    branches:
      - main
    
jobs:
  build:
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        os: [ubuntu-latest]
        node-version: [16.17.x]
    env: 
      DB : ${{secrets.DB }}
      cloud_name: ${{secrets.cloud_name}}
      api_key: ${{secrets.api_key}}
      api_secret: ${{secrets.api_secret}}
      jwtStrng: ${{secrets.jwtStrng}}
      PORT: ${{secrets.PORT}}
    steps:
      - uses: actions/checkout@v1
      - name: 'Use Node.js ${{ matrix.node-version }} on ${{ matrix.os }}'
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm test
      - run: npm run coverage
